name: 'Databrick Notebook Run'
description: 'Run a notebook in Databrick'
inputs:
  databrick-server-uri: # id of input
    description: 'URL of the databrick server'
    required: true
    default: "https://adb-XXXX.XX.azuredatabricks.net"
  databrick-token: # id of input
    description: 'Databrick Access Token'
    required: true
    default: "abcdefghijk"
  databrick-cluster-id: # id of input
    description: 'Databrick Cluster ID'
    required: true
    default: "abcdefghijk"
  databrick-local-path: # id of input
    description: 'Notebook in Databrick'
    required: true
    default: "github/workspace/notebooks"
  databrick-workspace-path: # id of input
    description: 'Workspace in Databrick'
    required: true
    default: "Users/xxx@domain.com"
  databrick-outfile-path: # file path to save process log
    description: 'File path to save process log'
    required: true
    default: "github/workspace/notebooks"
outputs:
  result: # id of output
    description: 'Result of the notebook'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.databrick-server-uri }}
    - ${{ inputs.databrick-token }}
    - ${{ inputs.databrick-cluster-id }}
    - ${{ inputs.databrick-local-path }}
    - ${{ inputs.databrick-workspace-path }}
    - ${{ inputs.databrick-outfile-path }}